### ISSUE TITLE
UI 디자인

### ISSUE THREAD

**Issue by Jiyul-Kim** [Jiyul-Kim/fullstack-community-board#1]
# UI 디자인
커뮤니티 게시판을 위한 UI 게시판 디자인을 제작해야 합니다.

## 링크
> https://www.figma.com/file/o6daW0jJVnlgOvbeKuZekX/CRUD-%EA%B5%AC%EC%84%B1?type=design&node-id=0%3A1&t=telj1JG3I11cTYFH-1

# Todo

- [x] 전체 Board (Board)
- [x] 상세 Board (예시, Notice)
- [x] 게시글 뷰(Article)
- [ ] 게시글 작성 뷰(Create)
- [x] Log In
- [x] Sign Up

# ETC
create 라우터의 경우 마크다운을 지원하는 textarea를 만들고 싶습니다.. 관련 사항 참고해서 제작하세요.
